site_name: superheld.app Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Nutzung: usage.md
  - Expertenmodus: configuration.md
  - FAQ: faq.md
  - Screenshots: screenshots.md

theme:
  name: material

# You can configure your own theme options, plugins, etc.
