baseURL = 'https://docs.superheld.app/'
languageCode = 'de'
defaultContentLanguage = 'de'
title = 'superheld.app Dokumentation'
theme = 'relearn'

# Menu
[[menu.main]]
  name = "🌐 Website"
  url = "https://superheld.app"
  weight = 100

[[menu.main]]
  name = "📱 GitHub"
  url = "https://github.com/benediktpoller/docs.superheld.app"
  weight = 110

# Params für Relearn Theme
[params]
  editURL = "https://github.com/benediktpoller/docs.superheld.app/edit/main/hugo-site/content/"
  
  # UI customization
  themeVariant = [ "relearn-light", "relearn-dark" ]
  showVisitedLinks = true
  disableSeoHrefLinks = false
  
  # Search
  [params.search]
    disable = false
    maxResults = 20
  
  # Code
  highlightLanguage = ["go", "html", "xml"]
  highlightWrap = true
  highlightInline = true
  highlightStyle = "monokai"

# Outputs
[outputs]
  home = ["HTML"]
  page = ["HTML"]

